//! User service — pure business logic, no model definitions, no HTTP types.
//!
//! ## Validation flow
//!
//!   `ValidatedJson`    — DTO field invariants (format, length, pattern) at HTTP edge
//!   `Username::new()`  — single-field domain invariant enforced by smart constructor
//!   `Email::new()`     — single-field domain invariant enforced by smart constructor
//!   `User::new()`      — mints a fresh `Id<User>` (domain owns its identity)
//!   `User::validate()` — cross-field aggregate invariant (username ≠ email local-part)
//!   `repo.save()`      — reached only when the aggregate is fully valid

use std::sync::Arc;

use rust_api::prelude::*;

use crate::models::domain::{Email, User, Username};
use crate::models::requests::CreateUserRequest;
use crate::models::responses::UserResponse;

pub struct UserService {
    repo: Arc<InMemoryRepository<User, Id<User>>>,
}

impl UserService {
    pub fn new() -> Self {
        Self {
            // `Id<User>` is always generated by `User::new()`, so is_new()
            // is never true and this generator is a safe fallback only.
            repo: Arc::new(InMemoryRepository::with_id_gen(Id::new)),
        }
    }

    /// Creates a new user.
    ///
    /// Each `?` is the monadic bind for `Result`: threads on `Ok`, short-
    /// circuits on `Err`.  No panics, no sentinels.
    pub async fn create(&self, req: CreateUserRequest) -> ValidationResult<UserResponse> {
        let username = Username::new(req.username)?;
        let email = Email::new(req.email)?;
        let user = User::new(username, email).validate()?;

        self.repo
            .save(user)
            .await
            .map_err(|e| vec![FieldError::new("repository", &e.to_string())])
            .map(|saved| UserResponse {
                id: saved.id.to_string(),
                username: saved.username.to_string(),
                email: saved.email.to_string(),
            })
    }
}
